package com.abrainyun.ldc.devops.metadata.entity;

import java.util.Date;
import java.util.Map;

public class MetaData {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meta_data.ID
     *
     * @mbg.generated Fri Sep 21 15:13:57 GMT+08:00 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meta_data.APP_ID
     *
     * @mbg.generated Fri Sep 21 15:13:57 GMT+08:00 2018
     */
    private String appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meta_data.TENANT_ID
     *
     * @mbg.generated Fri Sep 21 15:13:57 GMT+08:00 2018
     */
    private String tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meta_data.TYPE_NAME
     *
     * @mbg.generated Fri Sep 21 15:13:57 GMT+08:00 2018
     */
    private String typeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meta_data.UPDATED
     *
     * @mbg.generated Fri Sep 21 15:13:57 GMT+08:00 2018
     */
    private Date updated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meta_data.JSON
     *
     * @mbg.generated Fri Sep 21 15:13:57 GMT+08:00 2018
     */
    private String json;
    
    public Map getMappedJson() {
		return mappedJson;
	}

	public void setMappedJson(Map mappedJson) {
		this.mappedJson = mappedJson;
	}

	private Map mappedJson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meta_data.ID
     *
     * @return the value of meta_data.ID
     *
     * @mbg.generated Fri Sep 21 15:13:57 GMT+08:00 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meta_data.ID
     *
     * @param id the value for meta_data.ID
     *
     * @mbg.generated Fri Sep 21 15:13:57 GMT+08:00 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meta_data.APP_ID
     *
     * @return the value of meta_data.APP_ID
     *
     * @mbg.generated Fri Sep 21 15:13:57 GMT+08:00 2018
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meta_data.APP_ID
     *
     * @param appId the value for meta_data.APP_ID
     *
     * @mbg.generated Fri Sep 21 15:13:57 GMT+08:00 2018
     */
    public void setAppId(String appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meta_data.TENANT_ID
     *
     * @return the value of meta_data.TENANT_ID
     *
     * @mbg.generated Fri Sep 21 15:13:57 GMT+08:00 2018
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meta_data.TENANT_ID
     *
     * @param tenantId the value for meta_data.TENANT_ID
     *
     * @mbg.generated Fri Sep 21 15:13:57 GMT+08:00 2018
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meta_data.TYPE_NAME
     *
     * @return the value of meta_data.TYPE_NAME
     *
     * @mbg.generated Fri Sep 21 15:13:57 GMT+08:00 2018
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meta_data.TYPE_NAME
     *
     * @param typeName the value for meta_data.TYPE_NAME
     *
     * @mbg.generated Fri Sep 21 15:13:57 GMT+08:00 2018
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meta_data.UPDATED
     *
     * @return the value of meta_data.UPDATED
     *
     * @mbg.generated Fri Sep 21 15:13:57 GMT+08:00 2018
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meta_data.UPDATED
     *
     * @param updated the value for meta_data.UPDATED
     *
     * @mbg.generated Fri Sep 21 15:13:57 GMT+08:00 2018
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meta_data.JSON
     *
     * @return the value of meta_data.JSON
     *
     * @mbg.generated Fri Sep 21 15:13:57 GMT+08:00 2018
     */
    public String getJson() {
        return json;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meta_data.JSON
     *
     * @param json the value for meta_data.JSON
     *
     * @mbg.generated Fri Sep 21 15:13:57 GMT+08:00 2018
     */
    public void setJson(String json) {
        this.json = json;
    }
}